FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY stream-processing/metrics_worker.py .
COPY .env .

CMD ["python", "metrics_worker.py"]
